### ISSUE TITLE
License

### ISSUE THREAD

**Issue by AndreaMonzini** [wiSHFul97/FCurve-Cleaner#1]
Hello,
very interesting project !
Can you add the license ?

If it uses Blender Python API the license should be GPL

https://www.blender.org/about/license/

I pay attention on correct licenses for the addon i use for Blender projects.
And plan to test it as soon as possible :)

Thank you !

**Comment by wiSHFul97** [comment]
Hi, Thank you for reaching out!
I'll add the license very soon, I have an update for this addon.
But yes the license is "GPL". 

Thank you for your interest, let me know if you had any suggestions.
Regards!

**Comment by wiSHFul97** [comment]
License has been added!
