### ISSUE TITLE
not able to install

### ISSUE THREAD

**Issue by Vinayky86** [wiSHFul97/FCurve-Cleaner#2]
Hello thanks for this amazing addon..!!!  I tried to install many times,   but its not working, this is happening in system console. please guide if i do any wrong..thanks

addon_utils.disable: FCurve-Cleaner-main not disabled
Modules Installed (FCurve-Cleaner-main) from 'C:\\Users\\Pawan\\Desktop\\FCurve-Cleaner-main.zip' into 'C:\\Users\\Pawan\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons'
pip 20.2.3 from C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pip (python 3.9)
Collecting scipy
  Downloading scipy-1.8.1-cp39-cp39-win_amd64.whl (36.9 MB)
     |████████████████████████████████| 36.9 MB 6.8 MB/s
Requirement already satisfied: numpy<1.25.0,>=1.17.3 in c:\program files\blender foundation\blender 2.93\2.93\python\lib\site-packages (from scipy) (1.19.5)
Installing collected packages: scipy
Successfully installed scipy-1.8.1
WARNING: You are using pip version 20.2.3; however, version 22.1.2 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.EXE -m pip install --upgrade pip' command.

**Comment by wiSHFul97** [comment]
Hello,
Thank you for your interest!

I have some questions:
1- Did you try to open the Blender as  administrator?
2- Please open Blender in the normal way and enable the addon and see what happens (and print the log here). Does the addon enable successfully?

Thanks!

**Comment by Vinayky86** [comment]
Thank you very much..🙏🙏❤️ It works, really appreciate your kindness 🙏🙏
